# bundle exec jekyll serve --watch

# Site settings
title: "Scholars’ Lab"
name: "Scholars’ Lab"
email: scholarslab@virginia.edu
description: "The Scholars’ Lab"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maybe.scholarslab.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: scholarslab
permalink: /:categories/:title/

# Build settings
incremental: true
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  people:
    output: true
    permalink: /:collection/:name/
  research:
    output: true
    permalink: /:collection/:name/
  lab:
    output: true
    permalink: /:collection/:name/

header_pages:
  - about.md
  - people.md
  - blog.md
  - research.md
  - lab.md
  - search.html

exclude: [vendor]

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Plugins
plugins_dir:
  # - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-gist
  # - jekyll-feed
  # - jemoji
  # - liquid-md5
  - jekyll-lunr-js-search

# Lunr https://github.com/slashdotdash/jekyll-lunr-js-search
#Most of lunr stuff comes from this dude's repo https://github.com/justinrummel/jr.com-mm/commit/d2d0d620c5a5d0ddca283ecfe2eeb3b322f5b3b2
lunr_search:
  js_dir                  : "/js/lunr"
  min_length              : 3
