# bundle exec jekyll serve --watch

# Site settings
title: "Scholars' Lab"
name: "Scholars' Lab"
email: scholarslab@virginia.edu
description: "The Scholars' Lab"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: scholarslab

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  people:
    output: true
    permalink: /:collection/:name/
  research:
    output: true
    permalink: /:collection/:name/

header_pages:
  - about.md
  - research.md
  - graduate-fellowships.md
  - makerspace/makerspace.md
  - events.md
  - blog.md
  - people.md
